### ISSUE TITLE
SFTP

### ISSUE THREAD

**Issue by gtbu** [frakman1/ContaCam#16]
The ftp-upload is unsafe. Filezilla server (for example) offers sftp and generates  an own key.

There is https://github.com/kosinix/contacam-sftp-sync which needs node.js
( it would also be useful if all used ip-cams would appear in the  top-menu for choice)

**Comment by frakman1** [comment]
> The ftp-upload is unsafe

I assume you are speaking about the  'Command' section in the 'Advanced Camera Properties' of a camera and that you clicked on the 'FTP Upload' button?

<img width="300" alt="image" src="https://github.com/frakman1/ContaCam/assets/5826484/7032e338-5d23-409f-9a04-5f5ff876894c">

<p>&nbsp;</p>

If so, then that's just an example that populates the command parameters needed to perform an upload. It is triggered by the `Rec saving done` event. It appears to use `curl` under the covers.

Have you tried using the `sftp` command instead? You should be able to tailor it to do the same thing as `curl` but with pre-configured keys on your system. On my PC I run it as so (but have not tried it):

```bash
C:\Users\frak>sftp
usage: sftp [-46aCfpqrv] [-B buffer_size] [-b batchfile] [-c cipher]
          [-D sftp_server_path] [-F ssh_config] [-i identity_file] [-l limit]
          [-o ssh_option] [-P port] [-R num_requests] [-S program]
          [-s subsystem | sftp_server] destination

``` 

<p>&nbsp;</p>

> ( it would also be useful if all used ip-cams would appear in the top-menu for choice)

I am not sure what you mean here. The Command is a per-camera task so you don't need to select a camera, it's already selected at that point.

**Comment by gtbu** [comment]
I saw the ftp-button and not that You upload with curl.exe
The -k (or --insecure) option turns off curl's verification of the certificate.

**Comment by frakman1** [comment]
So have you tried removing the `--insecure` option and configuring it to work that way?

Incidentally, `curl` also supports uploading to `sftp://` URLs so you can use that with  `--key` and `--key-type` instead of username and password. See [man](https://curl.haxx.se/docs/manpage.html) page for syntax details.
